<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

In [65]:
import numpy as np
a=[[5,1,-2,0],
   [0,3,4,3],
   [2,3,1,1]]
b=[[1,-3],
   [2,-2],
   [3,-1],
   [0,0]]
c=[[5*1+1*2+-2*3+0,5*-3+1*-2+-2*-1+0],
   [0+6+12+0,0+-6+-4+0],
   [2+6+3+0,-6+-6+-1+0]]
np.dot(a,b)


array([[  1, -15],
       [ 18, -10],
       [ 11, -13]])

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [11]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [118]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
# Ваш код здесь
# ========
print(a)
print(b)

[[0.73641875 0.54493554 0.41830723 ... 0.02050073 0.47145463 0.31035203]
 [0.41355627 0.36450176 0.27473357 ... 0.13305113 0.07487659 0.52163544]
 [0.05090821 0.42323811 0.44826067 ... 0.91955535 0.98201895 0.73319633]
 ...
 [0.5986544  0.54816712 0.70330118 ... 0.68925636 0.78068006 0.94770695]
 [0.8999018  0.32434033 0.33152646 ... 0.54017951 0.42196132 0.40357341]
 [0.59137604 0.696298   0.11844246 ... 0.88161797 0.61285658 0.32888811]]
[[0.08884412 0.85362873 0.45989984 ... 0.20049865 0.40021728 0.74310254]
 [0.77167584 0.39875776 0.46310128 ... 0.01652282 0.03903942 0.62109333]
 [0.45857853 0.48142151 0.80190354 ... 0.01386435 0.64562406 0.51842003]
 ...
 [0.34597625 0.63763012 0.48259334 ... 0.37326186 0.18271994 0.33291169]
 [0.24882188 0.0032417  0.22267412 ... 0.52442294 0.67252392 0.96701484]
 [0.61416933 0.28743126 0.28940285 ... 0.73085873 0.73529334 0.74178171]]


In [115]:
def mult(a, b):
    return [[(sum([a[i][p]*b[p][k] for p in range(len(b))])) for k in range(len(b[0]))] for i in range(len(a))]

In [121]:
def np_mult(a, b):
    return np.dot(a,b)

In [122]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 1.49 s, sys: 9.44 ms, total: 1.5 s
Wall time: 1.51 s


In [123]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 4.62 ms, sys: 15.4 ms, total: 20 ms
Wall time: 69.1 ms


In [124]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

0.0

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [0]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.82238967 0.60895342 0.18699693] [0.10087098 0.31786346 0.05313135]


In [0]:
def scalar_product(a,b):
    #YOUR CODE

In [0]:
def np_scalar_product(a,b):
    #YOUR CODE

In [0]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 20 µs, sys: 1 µs, total: 21 µs
Wall time: 24.1 µs
CPU times: user 1.71 ms, sys: 66 µs, total: 1.78 ms
Wall time: 20.8 ms


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [0]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    #YOUR CODE

In [0]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[4, 6, 1, 5, 5],
       [9, 2, 6, 7, 4],
       [9, 2, 8, 3, 7],
       [7, 6, 2, 4, 7],
       [5, 9, 7, 6, 9]])

In [0]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 107 µs, sys: 4 µs, total: 111 µs
Wall time: 118 µs


18

### Задание 4
Напишите функцию, которая по данной последовательности $\{A_i\}_{i=1}^n$ строит последовательность $S_n$, где $S_k = \frac{A_1 + ... + A_k}{k}$.  

In [0]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    return #YOUR CODE

In [0]:
# зададим некоторую последовательность и проверим ее на ваших функциях. 
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3) 

%time S2 = np_sec_av(A)

CPU times: user 616 µs, sys: 0 ns, total: 616 µs
Wall time: 507 µs


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [0]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    #YOUR CODE

In [0]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)

CPU times: user 159 µs, sys: 0 ns, total: 159 µs
Wall time: 183 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [0]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    #YOUR CODE

In [0]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 51 µs, sys: 2 µs, total: 53 µs
Wall time: 58.7 µs
